### ISSUE TITLE
[Bug] Can not download models

### ISSUE THREAD

**Issue by dotancohen** [alichherawalla/offline-mobile-llm-manager#122]
## Description

After upgrading from 0.45 to 0.67, I can not download models. When I click a model (e.g. one of the Qwens) I see in the upper left "Download Failed", in the upper right "Done" and below them "undefined is not a function".

## Steps to Reproduce

1. Click `Models`
2. Click the Download icon (e.g. for `Qwen3-8B-Q5_0`)
3. There is no step 3

## Expected Behavior

Begin downloading the model

## Actual Behavior

Error message: `undefined is not a function`

## Environment

- **Platform**: Android
- **OS Version**: 16
- **Device**: Samsung S24 Ultra
- **App Version**: 0.67
- **Model in use**: none

**Comment by Patriot2407** [comment]
Does the same when I import a model

**Comment by alichherawalla** [comment]
0.67 has a known issue. please use 0.66 for now

**Comment by alichherawalla** [comment]
working on the fix for it

**Comment by alichherawalla** [comment]
this is fixed in 0.0.70. Published to the play store, and waiting on the app store

**Comment by LancerCZ** [comment]
I have 0.0.70 and it still won't download anything

**Comment by illigian** [comment]
I have tried the last version 0.0.81; the git version, the PlayStore version and the 0.0.66 version but neither of them can download any model. It just keep waiting at 0% and after a while it gives me back the error "download failed"

**Comment by alichherawalla** [comment]
the latest 0.83 should solve for it! Give it a go. https://github.com/alichherawalla/off-grid-mobile-ai/releases/tag/v0.0.83

**Comment by illigian** [comment]
I installed it immediately after your comment, put a model in download and it is simply stuck there at 0% for the last 20 min. No error this time but no progression.
Could be a workaround to give the direct link for the models and direct download? Se we can use a browser to download them externally from the app and then import them?

![Image](https://github.com/user-attachments/assets/1e542e66-69a5-4f85-9445-301c4097944f)
![Image](https://github.com/user-attachments/assets/61efe551-210d-4523-9cb0-92e0c0eea263)

**Comment by dishit-wednesday** [comment]
Hi. @illigian ,I want to resolve this issue.
are you on slack want to talk and gain some more insights so can fix this for once

**Comment by LancerCZ** [comment]
I have exactly the same problem

**Comment by dishit-wednesday** [comment]
hey @LancerCZ, this turned out to be a pretty nasty bug. it looks like the native http client used by some download managers, especially on samsung or redmagic devices, was cutting off or blocking huggingface’s long signed urls.

we’ve worked around this with @illigian’s help  and have a fix ready. just doing some final polishing and testing before the next release, should be out sometime next week.

if you’re up for it, i can share an apk with the fix on slack. it would really help us confirm it’s fully resolved on your device.

**Comment by Temder** [comment]
I have the same problem on my redmagic device and could test the fix

**Comment by dishit-wednesday** [comment]
hey @Temder can you try out the latest release v0.0.89 and let me know if it works for you as well ,has been fixed for some folks

**Comment by Temder** [comment]
In the latest version the downloading problem is fixed for me.

**Comment by dishit-wednesday** [comment]
Hey @Temder, glad to hear it's working for you! Really appreciate you taking the time to test it out 🙌

**Comment by dishit-wednesday** [comment]
Hey @dotancohen @LancerCZ , ! This has been confirmed fixed for both @illigian and @Temder.

We tracked down the root cause - it turned out to be a native http client issue on certain Android devices that was truncating or blocking HuggingFace's long signed URLs. We did a complete overhaul of the download handling to work around this.

Apologies for asking you to test earlier builds that didn't pan out. Could you give the latest release v0.0.89 a try and let us know if it's working on your end?
